baseurl = "/"
languageCode = "fr-fr"
languageLang = "fr"
title = "Beguelins.net"
disableKinds = ["RSS", "taxonomy", "term"]

[params]
images = []
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
